[database]
host = "carlitodatabase.database.windows.net"
port = 1433
name = "DataStorage"
user = "admin-owner"
password = "carlito99!!"
encrypt = "Yes"  # Use "Yes" or "No"
trust_server_certificate = "No"  # Use "Yes" or "No"
connection_timeout = 30