[database]
host = "carlitodatabase.database.windows.net"
port = 1433
name = "DataStorage"
user = "admin-owner"
password = "carlito99!!"
encrypt = true
trust_server_certificate = false
connection_timeout = 30